Repository GwaChaePah/front, pull requests merged in 2021-11, with the labels that each got.

#13 Ji kim main overall update
  index.html
  src/.DS_Store
  src/App.vue
  src/assets/loadingGif.gif
  src/components/Comments.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/NavHeader.vue
  src/components/NavPost.vue
  src/components/PostContent.vue
  src/components/PostItem.vue
  src/components/PostList.vue
  src/json/posts.json
  src/main.js
  src/router/Board.vue
  src/router/Login.vue
  src/router/NotFound.vue
  src/router/Post.vue
  src/router/Product.vue
  src/router/Search.vue
  src/router/index.js
  src/scss/main.scss
  src/store/auth.js
  src/store/index.js
  src/store/post.js
  src/store/product.js
Labels: enhancement

#18 FEAT: another major update
  index.html
  package-lock.json
  src/.DS_Store
  src/assets/GitHub-Mark-32px.png
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/NavPost.vue
  src/components/PostContent.vue
  src/components/PostItem.vue
  src/components/PostList.vue
  src/json/posts.json
  src/router/.DS_Store
  src/router/Board.vue
  src/router/Post.vue
  src/router/Product.vue
  src/router/Search.vue
  src/scss/main.scss
  src/store/.DS_Store
  src/store/auth.js
  src/store/post.js
  src/store/product.js
Labels: enhancement

#19 DESIGN + FIX: media query + click event prob fixed
  package-lock.json
  src/App.vue
  src/components/BoardItem.vue
  src/components/Comments.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/NavPost.vue
  src/components/PostContent.vue
  src/json/posts.json
  src/router/Board.vue
  src/router/NotFound.vue
  src/router/Post.vue
  src/router/Product.vue
  src/router/Search.vue
  src/scss/main.scss
  src/store/post.js
  src/store/product.js
Labels: enhancement

#23 Soooh sign in
  package-lock.json
  package.json
  src/App.vue
  src/components/Header.vue
  src/json/posts.json
  src/json/user.json
  src/jsuser.json
  src/router/Login.vue
  src/router/index.js
  src/store/index.js
  src/store/login.js
Labels: enhancement

#25 FEAT: connected with heroku(1) + header fix + dropdown menu syncing
  src/App.vue
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/main.js
  src/router/Board.vue
  src/router/NotFound.vue
  src/router/Post.vue
  src/router/Search.vue
  src/router/index.js
  src/store/index.js
  src/store/post.js
  src/store/product.js
Labels: enhancement

#27 FEAT: Heroku API connection
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/router/Post.vue
  src/store/post.js
  src/store/product.js
Labels: enhancement

#29 FIX: headers multipart-form data
  src/components/Comments.vue
  src/components/PostContent.vue
  src/components/UpdatePost.vue
  src/router/CreatePost.vue
  src/store/login.js
  src/store/post.js
  src/store/product.js
Labels: bug, enhancement, help wanted

#30 Ji kim store post fix
  src/.DS_Store
  src/App.vue
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/json/posts.json
  src/main.js
  src/router/Board.vue
  src/router/Product.vue
  src/router/Search.vue
  src/router/index.js
  src/scss/main.scss
  src/scss/typography.scss
  src/store/login.js
  src/store/post.js
  src/store/product.js
Labels: enhancement

#32 FEAT: pagination
  src/components/BoardMenu.vue
  src/components/BoardPage.vue
  src/components/Comments.vue
  src/components/Header.vue
  src/components/PostNav.vue
  src/router/Board.vue
  src/router/Search.vue
  src/store/post.js
Labels: enhancement

#34 DESIGN: pagination design update
  src/components/BoardPage.vue
Labels: enhancement

#40 글 작성, 글 수정시 권한 설정 및 리다이렉션 변경 + 게시판에 user_key에서 username 뜨도록 함
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/components/UpdatePost.vue
  src/router/CreatePost.vue
Labels: documentation, enhancement

#41 FIX: comment user_key -> username
  src/components/Comments.vue
Labels: bug

#42 register api connect! we can sign up #26
  package-lock.json
  src/App.vue
  src/router/Register.vue
  src/router/index.js
  src/store/index.js
  src/store/login.js
Labels: enhancement

#43 FIX: search results and mobileweb mediaquery fixed
  src/components/BoardItem.vue
  src/components/BoardPage.vue
  src/components/Comments.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/router/Board.vue
  src/store/product.js
Labels: enhancement

#46 FIX: board reload & username css
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/router/Board.vue
  src/store/index.js
  src/store/post.js
Labels: enhancement

#48 FIX: board reaching non-existing page error
  src/components/BoardMenu.vue
  src/components/Header.vue
Labels: enhancement

#50 register page css #26
  src/App.vue
  src/router/Login.vue
  src/router/Register.vue
  src/store/index.js
  src/store/login.js
Labels: enhancement

#53 FEAT: board relative timestamp
  src/components/BoardItem.vue
Labels: enhancement

#56 Feat: change token storage #55
  src/App.vue
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/router/CreatePost.vue
  src/router/Login.vue
  src/store/login.js
Labels: enhancement

#57 Login, Register, CreatePost CSS #54
  src/router/CreatePost.vue
  src/router/Login.vue
  src/router/Register.vue
Labels: design

#58 DESIGN: board and post design touchups
  src/components/Comments.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/router/Post.vue
  src/store/post.js
Labels: design

#59 DESIGN: css touchups
  src/assets/logo.png
  src/components/BoardItem.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/json/user.json
  src/router/Board.vue
  vue.config.js
Labels: design

#61 FIX: board and product css fix
  src/components/BoardItem.vue
  src/components/BoardMobile.vue
  src/router/Product.vue
Labels: design

#62 DESIGN: css touchups
  src/components/BoardMobile.vue
  src/components/Header.vue
  src/router/Board.vue
  src/router/Product.vue
  src/scss/main.scss
Labels: design

#63 FIX: board reload after post delete
  src/components/Comments.vue
  src/components/Header.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
  src/router/Board.vue
  src/router/Post.vue
  src/store/post.js
  static/제철42_글씨.png
  static/제철42_기본.png
  static/파비콘.png
Labels: bug, design

#66 FIX: prevent zoom on input focus
  index.html
Labels: bug

#67 find the post code
  index.html
  src/router/Login.vue
  src/router/Register.vue
  src/store/login.js
Labels: enhancement, design

#68 DESIGN: board css
  src/components/BoardItem.vue
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
Labels: design

#69 DESIGN: header css
  src/components/BoardMenu.vue
  src/components/Comments.vue
  src/components/Header.vue
  src/components/PostContent.vue
Labels: design

#70 DESIGN: mobiel board price button + comments css
  src/components/BoardMobile.vue
Labels: design

#71 FIX: post accepts newline and nonexisting posts goes to notfound
  src/components/PostContent.vue
  src/router/Post.vue
  src/store/post.js
Labels: bug

#72 DESIGN: post css
  src/components/Comments.vue
  src/components/PostContent.vue
  src/router/Product.vue
Labels: design

#73 FIX: image preview proto + line break
  src/components/PostContent.vue
  src/components/UpdatePost.vue
  src/router/CreatePost.vue
Labels: enhancement, help wanted

#74 FIX: board reload after post delete + 이달의 제철은?
  src/components/PostContent.vue
  src/router/Product.vue
Labels: bug, design

#75 BUG: Post update
  src/components/UpdatePost.vue
  src/router/CreatePost.vue
Labels: bug, enhancement

#77 Feat: change receive region code #76
  src/router/Login.vue
  src/router/NotFound.vue
  src/router/Register.vue
  vue.config.js
Labels: enhancement

#78 FIX: region tag
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
  src/store/post.js
Labels: enhancement

#79 FIX: post date after update
  src/components/PostContent.vue
  src/router/Post.vue
Labels: bug

#80 FIX: region tag
  src/components/BoardMenu.vue
Labels: bug

#81 login and refresh
  src/store/login.js
Labels: enhancement

#83 FIX: region tag (hopefully final fix)
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
Labels: bug

#84 FIX: loggin logout sync
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
  src/store/login.js
Labels: enhancement

#85 FIX: pagination for region
  src/store/login.js
  src/store/post.js
Labels: bug

#86 FIX: search board region toggle
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
  src/router/Product.vue
Labels: bug

#87 FIX: post nav back reload
  src/components/PostNav.vue
Labels: enhancement

#88 FIX: mobile post board nav
  src/components/BoardMenu.vue
  src/components/PostContent.vue
  src/components/PostNav.vue
Labels: bug

#89 Ji kim post store init to null
  src/store/post.js
  src/store/product.js
Labels: bug

#90 FIX: login region issue
  src/components/Header.vue
  src/store/login.js
Labels: bug

#92 FIX: region toggle final fix.. hopefully
  src/components/BoardMenu.vue
  src/components/Header.vue
  src/router/Board.vue
  src/store/post.js
Labels: bug
